params:
  epochs: 1
  batch_size: 32
  num_classes: 10
  loss_functions: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000



artifacts:
  artifacts_dir: artifacts
  models_dir: models
  plots_dir: plots
  checkpoint_dir: checkpoint


logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs